import React from "react";
import "../styles.css";
import Form from "./Form";

const NewUser = () => {
  /* The `newUserId` function was created because the `"id"` generated by the json server is a generated hash, 
  and this function will overwrite the generated hash 
  and be consistent with the test data provided in the `db.json` file 
  which are number strings that increment starting at `"1"`.
  */
  // const newUserId = () => `${this.props.usersCount + 1}`;

  const newUser = { name: "", email: "" };

  return <Form user={newUser} httpMethod={"POST"} />;
};

export default NewUser;
